version: '3'

services:
    nginx:
        build: ./docker/nginx
        ports:
            - '80:80'
        depends_on:
            - php
        volumes:
            - ./backend/laravel:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    php:
        build: ./docker/php
        volumes:
            - ./backend/laravel:/var/www/html/
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: ${DB_PORT}
            DB_DATABASE: ${MYSQL_DATABASE}
            DB_USERNAME: ${MYSQL_USER}
            DB_PASSWORD: ${MYSQL_PASSWORD}
        depends_on:
            - mysql

    mysql:
        build: ./docker/mysql
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            TZ: ${TZ}
        ports:
            - "${DB_PORT}:${DB_PORT}"
        volumes:
            - mysql-data:/var/lib/mysql

volumes:
    mysql-data: